name: Package DEB
on:
  release:
    types: [ created ]
jobs:
  build-amd64:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          scope: '@djthorpe'
          registry-url: 'https://npm.pkg.github.com'
      - name: NPM login
        run: |
          cat ~/.npmrc
          npm login --scope=@djthorpe --registry=https://npm.pkg.github.com
      - name: Install dependencies for Linux on amd64
        run: |
          sudo add-apt-repository ppa:jonathonf/ffmpeg-4 && sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler libprotobuf-dev \
            libmosquitto-dev \
            libavcodec-dev libavdevice-dev libavfilter-dev \
            libavformat-dev libavresample-dev libavutil-dev libchromaprint-dev
      - name: Build for Linux on amd64
        run: |
          make
      - name: Upload DEBs to release
        run: |
          TAG=`git describe --abbrev=0 --tags`
          gh release upload ${TAG} build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  build-arm64:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          scope: '@djthorpe'
          registry-url: 'https://npm.pkg.github.com'
      - name: NPM login
        run: |
          npm login --scope=@djthorpe --registry=https://npm.pkg.github.com
          cat ~/.npmrc
      - name: Build for Linux on arm64
        run: |
          make
      - name: Upload DEBs to release
        run: |
          TAG=`git describe --abbrev=0 --tags`
          gh release upload ${TAG} build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  build-arm:
    runs-on: [self-hosted, linux, arm]
    steps:
      - uses: actions/checkout@v2
      # ARM not supported by 'actions/setup-go@v2' on armhf
      - name: Install Go for armhf
        run: |
          install -d ${RUNNER_TEMP}/go
          curl -s -L https://golang.org/dl/go1.17.linux-armv6l.tar.gz | tar -C ${RUNNER_TEMP} -xz
          echo ${RUNNER_TEMP}/go/bin >> $GITHUB_PATH
          echo ${HOME}/go/bin >> $GITHUB_PATH
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          scope: '@djthorpe'
          registry-url: 'https://npm.pkg.github.com'
      - name: NPM login
        run: |
          npm login --scope=@djthorpe --registry=https://npm.pkg.github.com
          cat ~/.npmrc
      - name: Build for Linux on ARM
        run: |
          make
      - name: Upload DEBs to release
        run: |
          TAG=`git describe --abbrev=0 --tags`
          gh release upload ${TAG} build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
