name: Package DEB
on:
  release:
    types: [ created ]
jobs:
  build-amd64:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Build for Linux on amd64
        run: |
          sudo apt-get install -y libmosquitto-dev
          make
      - name: Upload DEBs to release
        run: |
          TAG=`git describe --abbrev=0 --tags`
          gh release upload ${TAG} build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-arm64:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Build for Linux on arm64
        run: |
          make
      - name: Upload DEBs to release
        run: |
          TAG=`git describe --abbrev=0 --tags`
          gh release upload ${TAG} build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-arm:
    runs-on: [self-hosted, linux, arm]
    steps:
      - uses: actions/checkout@v2
      # ARM not supported by 'actions/setup-go@v2' on armhf
      - name: Install Go for armhf
        run: |
          install -d ${RUNNER_TEMP}/go
          curl -s -L https://golang.org/dl/go1.17.linux-armv6l.tar.gz | tar -C ${RUNNER_TEMP} -xz
          echo ${RUNNER_TEMP}/go/bin >> $GITHUB_PATH
          echo ${HOME}/go/bin >> $GITHUB_PATH
      - name: Build for Linux on ARM
        run: |
          make
      - name: Upload DEBs to release
        run: |
          TAG=`git describe --abbrev=0 --tags`
          gh release upload ${TAG} build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
